### ISSUE TITLE
Containers stats is broken in Docker-py 6.1.0 

### ISSUE THREAD

**Issue by nicolargo** [docker/docker-py#3118]
Look like Docker-Py breaks the API to retrieve stats from containers. 

With Docker 6.0.1 (on Ubuntu 22.04):

```
>>> import docker
>>> c = docker..from_env()
>>> for i in c.containers.list():
...     i.stats(decode=True)
... 
<generator object APIClient._stream_helper at 0x7f236f354eb0>
```

With Docker 6.1.0:

```
>>> import docker
>>> c = docker..from_env()
>>> for i in c.containers.list():
...     i.stats(decode=True)
... 
Never return anything...
```

Additional information:

```
$ cat /etc/os-release 
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

$ docker version
Client: Docker Engine - Community
 Version:           23.0.1
 API version:       1.42
 Go version:        go1.19.5
 Git commit:        a5ee5b1
 Built:             Thu Feb  9 19:46:56 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          23.0.1
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.19.5
  Git commit:       bc3805a
  Built:            Thu Feb  9 19:46:56 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.19
  GitCommit:        1e1ea6e986c6c86565bc33d52e34b81b3e2bc71f
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
```

Source: https://github.com/nicolargo/glances/issues/2366

**Comment by nicolargo** [comment]
Corrected by forcing stream=True. Does the default value for stream change between Docker-Py 6.0.1 and 6.1.0 ?

```
>>> import docker
>>> c = docker..from_env()
>>> for i in c.containers.list():
...     i.stats(stream=True, decode=True)
... 
Works !
```

**Comment by RazCrimson** [comment]
Just to note, even passing the `stream=True` with the stats API does not fix this issue.

The above PR should fix the issue.

![image](https://user-images.githubusercontent.com/52282402/236643139-37a9103b-2da0-422d-be50-664c2d07e204.png)
